### ISSUE TITLE
Various small issues

### ISSUE THREAD

**Issue by hmarceau** [malavv/c1d3r#1]
Great job!

When entering a liquid quantity in milliliters, and after changer the values for liters, the recipe (steps) are unchanged. This is the main bug ^^.

Please detect out of range efficiencies (i.e. more than 100% or < 1%) or specify if efficiencies should be (0-1) or (0-100%).
If the required PH is higher than the PH of the juice, the program still suggest to add acid.
Entering weird densities, yeast efficiencies, low desired alcohol content or ppg ended up in adding negative amount of sugar to the recipe. Just for your information ;-).

**Comment by malavv** [comment]
Thank you for this bug report!
- For the issue of mishandling units in inputs. This functionality was removed altogether from **v2**. Now all units must be entered, and will be presented in their SI form (+Litres even though it's not SI)
- Manual input of yeast efficiency was only available in a custom recipe. We are moving toward having mainly pre-made recipe. But if we do again, we'll keep this in mind.
- PH should be fixed in commit 1352d35e99d0bf2cfaf7279a7ca4f65730677a9c
- Sugar addition is still a concern and has been moved to issue #2 for further reference.
