### ISSUE TITLE
Missing volume amounts in some cases

### ISSUE THREAD

**Issue by erikhicks** [malavv/c1d3r#11]
Example:

2.2 **Mix-in kg** of table sugar thoroughly.
2.3 Stir liquid thoroughly for at least 2 minutes.
2.4 Be warned that due to the sugar addition, the final volume will increase **from 3.7 to L.**

Expecting volume numbers here, or some indication if no sugar is needed.

**Comment by malavv** [comment]
Thanks @erikhicks for the report.

In order to ensure reproducibility of the issue, could you confirm if what you are seeing is the result of : 
1. Leaving some fields empty in the ingredients or "Juice" page.
2. Clicking next to move to the guide page.

Is it how you got to this state? If not, please provide more information to ensure reproducibility. Nevertheless, it is a known issue that the user should not be offered to move to the next step without filling all required data fields.

**Comment by tk-421** [comment]
I can also reproduce the **from x to L** bug. 

Attached screen of my data entry:

<img width="1133" alt="screen shot 2016-09-23 at 5 37 11 pm" src="https://cloud.githubusercontent.com/assets/3330975/18804761/6aeca49a-81b4-11e6-849c-25f94a9a8c14.png">

**Comment by malavv** [comment]
Thanks for the update @tk-421, 
From your screenshot, you only filled Ingredients 0, 1 and Personalization 0. All other fields have the grayed out placeholder value. The amount of chaptalization sugar will be computer using the Ingredient 1, 2, and Personalization 2. There is one field missing then to compute it.

Nevertheless, the lack of guidance and explanation _is an issue_.  I will create another issue for this and it should be fix in a patch release in the following week.

Thanks again!

**Comment by malavv** [comment]
Fixed in v2.1.1
